### ISSUE TITLE
getRecords is not defined

### ISSUE THREAD

**Issue by kepair** [romualdr/node-njalla-dns#1]
Hi  @romualdr,

First, thanks for this, it's literally the only one I found for Nja.la.
I'm creating a simple script that checks and updates the IP of the A records if my public IP changes, however, I'm getting the following error when trying to get the records.

It's strange because the rest of the commands work without problems (getDomains, add, remove, update)m and I can see getRecords defines in the node-modules as the rest of them.

I wrote the script, ran 'npm i njalla-dns' inside the folder and tried to run it.

The script:
```
const { login, getDomains, add } = require('njalla-dns')

;(async function main() {
    await login('huehue@huehue.hue', 'huehuehuehue')

    const domains = await getDomains()
    console.log(domains) //I can see the domains printed out
    await add(domains[0], 'A', 'test', '192.168.10.0', 3600) //I can see te record creted in the web
    const records = await getRecords(domains[0]) //This shows the error below
    console.log(records)   
})()
```
The error:
```
(node:18884) UnhandledPromiseRejectionWarning: ReferenceError: getRecords is not defined
    at main (C:\workspace\njalla-dns-updater\update-ip.js:17:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Could it be something on my end? This seemed to be pretty straight forward.

Thanks,
kepair

**Comment by romualdr** [comment]
Hey @kepair,

The problem is that you don't require the function `getRecords` in the first line of your script:
`const { login, getDomains, add } = require('njalla-dns')`

It should be
`const { login, getDomains, getRecords, add } = require('njalla-dns')`

It will probably work once you made the change.
Regards,
Romuald

**Comment by kepair** [comment]
Hi @romualdr,

Thanks, newbie mistake, of course it works now.

Kr,
kepair
