### ISSUE TITLE
njalla-dns/lib/dns.js query bug

### ISSUE THREAD

**Issue by mobsikx** [romualdr/node-njalla-dns#21]
I had to change the function like this in order to be able update a record with the name === '@'

`async function _findRecords(domain, query) {
    return (await this.getRecords(domain)).filter((r) => r.id === query || r.id === query.id)`

my call:
`await dns.update('SOME_DOMAIN', records.find((r) => r.id === SOME_ID), { content: 'SOME_IP' })`

**Comment by romualdr** [comment]
Hello, sorry about the delay.

Indeed, I think njal.la made some changes not long ago about their API and it looks like I might need to update the code accordingly.

Thanks for the heads up !
